apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: NodePort
  selector:
    app: ecommerce-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
